version: "3.8"

services:
  nginx:
    build: requirements/nginx/.
    image: nginx
    container_name: nginx
    depends_on:
      wordpress:
        condition: service_started
      mariadb:
        condition: service_started
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    environment:
      NGINX_CERTIFICATE: /run/secrets/nginx_crt
      NGINX_KEY: /run/secrets/nginx_key
    secrets:
      - nginx_crt
      - nginx_key
    restart: on-failure
  wordpress:
    build: requirements/wordpress/.
    image: wordpress
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_started
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    environment:
      WP_ADMIN_PWD_FILE: /run/secrets/wp_admin_pwd
      WP_PWD_FILE: /run/secrets/wp_pwd
      DB_ADMIN_PWD_FILE: /run/secrets/db_admin_pwd
    secrets:
      - wp_admin_pwd
      - wp_pwd
      - db_admin_pwd
    restart: on-failure
  mariadb:
    build: requirements/mariadb/.
    image: mariadb
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    environment:
      DB_ADMIN_PWD_FILE: /run/secrets/db_admin_pwd
      DB_PWD_FILE: /run/secrets/db_pwd
    secrets:
      - db_admin_pwd
      - db_pwd
    restart: on-failure

networks:
  inception:
    name: inception

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/hiono/data/web
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/hiono/data/database
      o: bind
      type: none

secrets:
  wp_admin_pwd:
    file: /home/hiono/Inception/secrets/wp_admin_pwd.txt
  wp_pwd:
    file: /home/hiono/Inception/secrets/wp_pwd.txt
  db_admin_pwd:
    file: /home/hiono/Inception/secrets/db_admin_pwd.txt
  db_pwd:
    file: /home/hiono/Inception/secrets/db_pwd.txt
  nginx_crt:
    file: /home/hiono/Inception/secrets/nginx-selfsigned.crt
  nginx_key:
    file: /home/hiono/Inception/secrets/nginx-selfsigned.key
