CREATE DATABASE IF NOT EXISTS DB_NAME;
CREATE USER IF NOT EXISTS 'DB_ADMIN_USER'@'%' IDENTIFIED BY 'DB_ADMIN_PWD';
GRANT ALL PRIVILEGES ON *.* TO 'DB_ADMIN_USER'@'%' WITH GRANT OPTION;
CREATE USER IF NOT EXISTS 'DB_USER'@'%' IDENTIFIED BY 'DB_PWD';
FLUSH PRIVILEGES;
